# Generated by Django 4.0.4 on 2022-04-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Issue'), (2, 'Feature')])),
                ('priority', models.SmallIntegerField(choices=[(1, 'Cab High'), (2, 'Medium'), (3, 'Low')])),
                ('status', models.SmallIntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'In Review'), (4, 'Closed')])),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
